trigger:
- none

pool:
  #vmImage: 'ubuntu-latest'
  name: 'Azure Pipelines'

jobs:
- job: HelmDeploy
  displayName: "Helm Deploy to Kubernetes"
  steps:
  
  - task: KubernetesManifest@0
    displayName: Deploy K8s manifests
    inputs:
      kubernetesServiceConnection: 'aks-connection'
      namespace: app-dev
      manifests: '$(Build.SourcesDirectory)/kube-manifests/'
